name: Build Leanpub version and push to 'leanpub' branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ fix-leanpub-ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: ./build-leanpub.py

      # Runs a set of commands using the runners shell
      - name: Push
        run: .travis/push.sh

